### ISSUE TITLE
NullpointerException when using "com.moowork.node" plugin.

### ISSUE THREAD

**Issue by asaarnak** [stevesaliman/gradle-properties-plugin#17]
1. build.gladle
```gradle
plugins {
  id "com.moowork.node" version "0.8"
  id 'net.saliman.properties' version '1.4.2'
}
```
2.Gives me stacktrace when running ```gradle```
3.Stacktrace
<pre>
c:\A\PROJECTS\timetracker\timetracker-front>gradle --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\A\PROJECTS\timetracker\timetracker-front\build.gradle' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'net.saliman.properties', version: '1.4.2']
> Cannot set property 'requiredProperty' on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'net.saliman.properties', version: '1.4.2']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:168)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:124)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:131)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.NullPointerException: Cannot set property 'requiredProperty' on null object
        at net.saliman.gradle.plugin.properties.PropertiesPlugin$_registerTaskListener_closure6.doCall(PropertiesPlugin.groovy:355)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:482)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:55)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
        at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin.registerTaskListener(PropertiesPlugin.groovy:352)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin.this$2$registerTaskListener(PropertiesPlugin.groovy)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin$this$2$registerTaskListener$4.callCurrent(Unknown Source)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin.apply(PropertiesPlugin.groovy:139)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin.apply(PropertiesPlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$4.run(DefaultPluginRequestApplicator.java:126)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:156)
        ... 33 more

BUILD FAILED

Total time: 3.791 secs

</pre>

**Comment by stevesaliman** [comment]
I'm having trouble reproducing this one.  From the code, the failure happens when I tried to add something to the "ext" property of a task, but I thought that all tasks would have this property, so I don't understand why something would be null there, and I can't get this to happen in any of my projects that use this plugin.

What version of Gradle are you using?

**Comment by asaarnak** [comment]
It was 2.2.1, i'll try to reproduce it tomorrow.

**Comment by stevesaliman** [comment]
I can reproduce it now, by adding com.moowork.node plugin to my test project.  

This turns out to be a problem with the node plugin's SetupTask object, with overrides Gradle's standard ```ext``` property with something incompatible.  To make matters worse, they start the property out with a null value.  I've reported this issue to them at https://github.com/srs/gradle-node-plugin/issues/41 if you want to track the issue's progress.

I could try to work around the issue by checking the task's ext object, but since Gradle documentation states that all objects should have the object I'm looking for, I'd prefer to have the node plugin's authors fix the issue on their end.

**Comment by asaarnak** [comment]
Thanks, i have subscribed to the new issue.
